import {DataLoader, Tab, Tabs} from 'argo-ui';
import * as React from 'react';
import {BehaviorSubject} from 'rxjs';

import {EventsList} from '../../../shared/components';
import {ErrorBoundary} from '../../../shared/components/error-boundary/error-boundary';
import {AppContext, Context} from '../../../shared/context';
import * as models from '../../../shared/models';
import {Application, Event, ResourceNode, State} from '../../../shared/models';
import {services} from '../../../shared/services';
import {ResourceIcon} from '../../../shared/components/resource/resource-icon';
import {ResourceLabel} from '../../../shared/components/resource/resource-label';
import {ApplicationNodeInfo} from '../../../shared/components/resource/application-node-info/application-node-info';
import * as AppUtils from '../../../applications/components/utils';
import './resource-details.scss';

interface AppSetGeneratedAppDetailsProps {
    // The parent ApplicationSet (used for navigation context only; the generated Application's own
    // manifest and status are loaded from the Application itself).
    application: Application;
    selectedNode: ResourceNode;
    appCxt: AppContext;
    appChanged?: BehaviorSubject<models.AbstractApplication>;
}

// AppSetGeneratedAppDetails renders the read-only details view for an Application node generated by an
// ApplicationSet. The generated Application's live manifest is loaded from the Application itself: there
// is no diff/desired manifest, no sync/resource actions, and only "Open Application" and "Delete" buttons.
export const AppSetGeneratedAppDetails = (props: AppSetGeneratedAppDetailsProps) => {
    const {selectedNode, application} = props;
    const appContext = React.useContext(Context);

    const buildTabs = (liveState: State, events: Event[], links: models.LinksResponse): Tab[] => {
        const tabs: Tab[] = [
            {
                title: 'SUMMARY',
                icon: 'fa fa-file-alt',
                key: 'summary',
                content: (
                    <ApplicationNodeInfo
                        application={application}
                        live={liveState}
                        controlled={null}
                        node={selectedNode}
                        links={links}
                        readonly={true}
                        readOnlyGeneratedApplication={true}
                    />
                )
            }
        ];

        if (liveState) {
            const numErrors = events.filter(event => event.type !== 'Normal').reduce((total, event) => total + event.count, 0);
            tabs.push({
                title: 'EVENTS',
                icon: 'fa fa-calendar-alt',
                badge: (numErrors > 0 && numErrors) || null,
                key: 'events',
                content: (
                    <div className='application-resource-events'>
                        <EventsList events={events} />
                    </div>
                )
            });

            const extensionTabs = selectedNode?.kind ? services.extensions.getResourceTabs(selectedNode?.group || '', selectedNode?.kind) : [];
            extensionTabs.forEach((tabExtensions, i) => {
                tabs.push({
                    title: tabExtensions.title,
                    key: `extension-${i}`,
                    content: (
                        <ErrorBoundary message={`Something went wrong with Extension for ${liveState?.kind || 'resource of unknown kind'}`}>
                            <tabExtensions.component tree={null} resource={liveState} application={application} />
                        </ErrorBoundary>
                    ),
                    icon: tabExtensions.icon
                });
            });
        }

        return tabs;
    };

    const searchParams = new URLSearchParams(appContext.history.location.search);
    const tab = searchParams.get('tab');

    return (
        <div style={{width: '100%', height: '100%'}}>
            {selectedNode && (
                <DataLoader
                    noLoaderOnInputChange={true}
                    input={selectedNode.resourceVersion}
                    load={async () => {
                        // Load the live manifest from the generated Application itself (the parent object is an
                        // ApplicationSet, not an Application).
                        const loaded = await services.applications
                            .get(selectedNode.name, selectedNode.namespace, 'application')
                            .then(app => ({liveState: app as unknown as State, denied: false}))
                            .catch((err): {liveState: State; denied: boolean} => ({
                                liveState: null,
                                // Treat 404 as a lack of permission (the API hides existence on RBAC denial).
                                denied: err?.status === 403 || err?.status === 404
                            }));
                        const events = loaded.liveState ? await services.applications.events(selectedNode.name, selectedNode.namespace).catch((): Event[] => []) : [];
                        return {
                            liveState: loaded.liveState,
                            events,
                            links: null as models.LinksResponse,
                            denied: loaded.denied
                        };
                    }}>
                    {data => (
                        <React.Fragment>
                            <div className='resource-details__header'>
                                <div style={{display: 'flex', flexDirection: 'column', marginRight: '15px', alignItems: 'center', fontSize: '12px'}}>
                                    <ResourceIcon group={selectedNode.group} kind={selectedNode.kind} />
                                    {ResourceLabel({kind: selectedNode.kind})}
                                </div>
                                <div className='resource-details__header-name'>
                                    <h1 className='resource-details__header-title'>{selectedNode.name}</h1>
                                    <span className='resource-details__header-status'>
                                        {(() => {
                                            const generatedApp = data.liveState as unknown as Application;
                                            return (
                                                <>
                                                    {generatedApp?.status?.health && <AppUtils.HealthStatusIcon state={generatedApp.status.health} />}
                                                    {generatedApp?.status?.sync?.status && (
                                                        <span style={{marginLeft: '5px'}}>
                                                            <AppUtils.ComparisonStatusIcon status={generatedApp.status.sync.status} />
                                                        </span>
                                                    )}
                                                </>
                                            );
                                        })()}
                                    </span>
                                </div>
                                <div className='resource-details__header-actions'>
                                    {(() => {
                                        const linkInfo = AppUtils.getApplicationLinkURLFromNode(selectedNode, appContext.baseHref);
                                        return (
                                            <>
                                                <a
                                                    href={linkInfo.url}
                                                    target={linkInfo.isExternal ? '_blank' : '_self'}
                                                    rel={linkInfo.isExternal ? 'noopener noreferrer' : undefined}
                                                    style={{marginLeft: 'auto', marginRight: '5px'}}
                                                    className='argo-button argo-button--base'>
                                                    <i className='fa fa-external-link-alt' /> <span className='show-for-large'>OPEN APPLICATION</span>
                                                </a>
                                                <button
                                                    onClick={() => AppUtils.deleteApplication(selectedNode.name, selectedNode.namespace, appContext)}
                                                    style={{marginRight: '5px'}}
                                                    className='argo-button argo-button--base'>
                                                    <i className='fa fa-trash' /> <span className='show-for-large'>DELETE</span>
                                                </button>
                                            </>
                                        );
                                    })()}
                                </div>
                            </div>
                            {data.denied ? (
                                <div className='white-box'>
                                    <div className='white-box__details'>You do not have permission to view this Application.</div>
                                </div>
                            ) : (
                                <Tabs
                                    navTransparent={true}
                                    tabs={buildTabs(data.liveState, data.events, data.links)}
                                    selectedTabKey={tab}
                                    onTabSelected={selected => appContext.navigation.goto('.', {tab: selected}, {replace: true})}
                                />
                            )}
                        </React.Fragment>
                    )}
                </DataLoader>
            )}
        </div>
    );
};
